name: webapi
services:
    webapi:
        ports:
        - 7080:80
        # - 7443:443
        environment:
        - GOSqlConnection__ConnectionString=Server=green-onion-dev-sql-server-1;Database=GreenOnionDb;User ID=sa;Password=Gr33n0n!on;TrustServerCertificate=True;
        - ASPNETCORE_ENVIRONMENT=Development
        - HTTP_PORTS=80
        # - HTTPS_PORTS=443
        build:
            dockerfile: DockerFile.webapi
            context: .
        networks:
        - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
