name: webapi
services:
    webapi:
        ports:
        - 7080:80
        # - 7443:443
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - HTTP_PORTS=80
        # - HTTPS_PORTS=443
        build:
            dockerfile: DockerFile.webapi
            context: .
        networks:
        - backend

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
